---
title: "EDA_breast_cancer"
author: "Autor: Daniel Quesada"
date: "Fecha de la publicación: `r Sys.Date()`"
output: html_document
---

# Contexto
El dataset objeto de este Exploratory Data Analysis (EDA) es una muestra de mujeres pacientes de cancer de mama de entre 2006 y 2010. Entre las variables de la BBDD se encuentra si el paciente sobrevivió al cancer o no.

Este dataset ha sido recogido de Kaggle. Se encuentra en la siguiente dirección:

[Dataset Breast Cancer](https://www.kaggle.com/datasets/reihanenamdari/breast-cancer)




```{r s}
Breast_Cancer<- read.csv('Breast_Cancer.csv')
head(Breast_Cancer)
```

```{R }
str(Breast_Cancer)
```

```{r}
Breast_Cancer$Status <-factor(Breast_Cancer$Status)
levels(Breast_Cancer$Status)
```



```{R }
#levels(Breast_Cancer$Status)
summary(Breast_Cancer)
```

```{r}
#table(Breast_Cancer$Status)
prop.table(table(Breast_Cancer$Status))
#table(Breast_Cancer$Status,Breat_Cancer$Race)
```

```{r}
#boxplot(Breast_Cancer$Age)
hist(Breast_Cancer$Age)
```


```{r}
dim(Breast_Cancer)
```



https://github.com/carmenlancho/MDS
Iris_sinlogo ->raw->



