---
title: "Lectura Datos"
author: "Desiderio"
date: "11/11/2022"
output: html_document
---

Para aprender a leer los datos:

```{r setup, include=FALSE}
datos <- read.csv("Breast_Cancer.csv")
```

Cuando queremos decirle a R que nos de un factor tenemos que hacer lo siguiente:
```{r setup, include=FALSE}
datos$Status <- factor(datos$Status)
```

```{r setup, include=FALSE}
datos$Race <- factor(datos$Race)
```

```{r setup, include=FALSE}
datos$Marital.Status <- factor(datos$Marital.Status)
```

```{r setup, include=FALSE}
datos$T.Stage <- factor(datos$T.Stage)
```

```{r setup, include=FALSE}
datos$N.Stage <- factor(datos$N.Stage)
```

```{r setup, include=FALSE}
datos$X6th.Stage <- factor(datos$X6th.Stage)
```

```{r setup, include=FALSE}
datos$differentiate <- factor(datos$differentiate)
```

```{r setup, include=FALSE}
datos$Grade <- factor(datos$Grade)
```

```{r setup, include=FALSE}
datos$A.Stage <- factor(datos$A.Stage)
```

```{r setup, include=FALSE}
datos$Estrogen.Status <- factor(datos$Estrogen.Status)
```

```{r setup, include=FALSE}
datos$Progesterone.Status <- factor(datos$Progesterone.Status)
```

Para aprender a leer los datos:
```{r setup, include=FALSE}
head(datos)
```

```{r setup, include=FALSE}
str(datos)
```

```{r setup, include=FALSE}
summary(datos)
```

###Sumario individual de cada variable
```{r}
summary(datos$Age)
```

```{r}
summary(datos$Race)
```

```{r}
summary(datos$Marital.Status)
```

```{r}
summary(datos$T.Stage)
```

```{r}
summary(datos$N.Stage)
```

```{r}
summary(datos$X6th.Stage)
```

```{r}
summary(datos$differentiate)
```

```{r}
summary(datos$Grade)
```

```{r}
summary(datos$A.Stage)
```

```{r}
summary(datos$Tumor.Size)
```

```{r}
summary(datos$Estrogen.Status)
```

```{r}
summary(datos$Progesterone.Status)
```

```{r}
summary(datos$Regional.Node.Examined)
```

```{r}
summary(datos$Reginol.Node.Positive)
```

```{r}
summary(datos$Survival.Months)
```

```{r}
summary(datos$Status)
```